{{- if .Values.ntaApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bustracker.fullname" . }}-secrets
  labels:
    {{- include "bustracker.labels" . | nindent 4 }}
type: Opaque
stringData:
  nta-api-key: {{ .Values.ntaApiKey | quote }}
{{- end }}
